version: '3.3'
services:
  db:
    container_name: postgres
    image: "postgres:12.2"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./init-tables.sql:/docker-entrypoint-initdb.d/init-tables.sql
    env_file:
      - env
    networks:
      - db_nw
  bot:
    container_name: bot-driver
    build: .
    env_file:
      - env
    networks:
      - db_nw
    depends_on:
      - db
networks:
  db_nw:
    driver: bridge